AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  microservices

  The entire backend API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Layers: 
      - !Ref ApiLayer
    Timeout: 5
    MemorySize: 256
    Runtime: nodejs14.x
    CodeUri: ./
    Environment:
      Variables:
        PG_HOST:
        PG_PORT:
        PG_DATABASE:
        PG_USER:
        PG_PASSWORD:
        JWT_SECRET:
        STRIPE_SECRET_KEY:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: backend
      StageName: dev
  Webhooks:
    Type: AWS::Serverless::Api
    Properties:
      Name: backend-webhooks
      StageName: dev
  AuthSignupPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/signup/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: POST
            RestApiId: !Ref Api
  AuthLoginPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/login/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref Api
  AuthVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: POST
            RestApiId: !Ref Api
  UsersIdGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
            RestApiId: !Ref Api
  UsersIdVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/verify
            Method: POST
            RestApiId: !Ref Api
  UsersIdInvitesGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/invites/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/invites
            Method: GET
            RestApiId: !Ref Api
  SchoolsPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdInvitesPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/invites/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/invites
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdJoinPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/join/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/join
            Method: POST
            RestApiId: !Ref Api
  WebhookStripe:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/webhooks/stripe/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /stripe
            Method: POST
            RestApiId: !Ref Webhooks
  ApiLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - nodejs14.x
      Description: API Layer
      LayerName: api
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.lambdaHandler
  #     Runtime: nodejs14.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /hello
  #           Method: get
  #   Metadata: # Manage esbuild properties
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - app.ts

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
