AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  microservices

  The entire backend API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Layers: 
      - !Ref ApiLayer
    Timeout: 5
    Runtime: nodejs14.x
    CodeUri: ./
    Environment:
      Variables:
        PGHOST:
        PGPORT:
        PGDATABASE:
        PGUSER:
        PGPASSWORD:
        JWTPRIVATE:

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: backend
      StageName: dev
  AuthSignupPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/signup/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: POST
            RestApiId: !Ref Api
  AuthLoginPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/login/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref Api
  AuthVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: POST
            RestApiId: !Ref Api
  UsersIdGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
            RestApiId: !Ref Api
  UsersIdVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/verify
            Method: POST
            RestApiId: !Ref Api
  ApiLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - nodejs14.x
      Description: API Layer
      LayerName: api
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.lambdaHandler
  #     Runtime: nodejs14.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /hello
  #           Method: get
  #   Metadata: # Manage esbuild properties
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - app.ts

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
