AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  microservices

  The entire backend API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Layers: 
      - !Ref ApiLayer
    Timeout: 8
    MemorySize: 256
    Runtime: nodejs14.x
    CodeUri: ./
    Environment:
      Variables:
        PG_HOST: "dev-db.cwmhht230lam.us-west-1.rds.amazonaws.com"
        PG_PORT: "5432"
        PG_DATABASE: "dev"
        PG_USER: "api"
        PG_PASSWORD: "vLc^?*QvP?0~F^S>f\"r,2m?`DC\\[4Txo?BAII8+t\":J~/"
        JWT_SECRET: "UGtAwAsERbKGWkEREITdgImIjzpLZRruzGLHxqHwMHeOiBzKnE"
        STRIPE_SECRET_KEY: "sk_test_51JetjJGsHxGKM7KB2BHdGP0jnER9Rp1kNaSVb4sgQvtO80svh5IxpwzZCLFUBhklzX7DUGDyt9gjIFYwJ0lGy19B00fTo3pYtV"
        SENDGRID_API_KEY: "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"
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: backend
      StageName: dev
      Domain:
        DomainName: "api.matmaster.app"
        BasePath:
         - dev
        CertificateArn: "arn:aws:acm:us-west-1:595951039957:certificate/2953f9ee-b494-42b9-8746-cb24da17319e"
  Webhooks:
    Type: AWS::Serverless::Api
    Properties:
      Name: backend-webhooks
      StageName: dev
  AuthSignupPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/signup/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: POST
            RestApiId: !Ref Api
  AuthLoginPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/login/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref Api
  AuthVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/auth/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: POST
            RestApiId: !Ref Api
  UsersIdGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
            RestApiId: !Ref Api
  UsersIdPATCH:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/PATCH/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: PATCH
            RestApiId: !Ref Api
  UsersIdVerifyPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/verify/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/verify
            Method: POST
            RestApiId: !Ref Api
  UsersIdInvitesGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/invites/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/invites
            Method: GET
            RestApiId: !Ref Api
  UserIdSchoolsGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/schools/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/schools
            Method: GET
            RestApiId: !Ref Api
  UserIdBillingGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/billing/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/billing
            Method: GET
            RestApiId: !Ref Api
  UserIdBillingPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/users/{id}/billing/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users/{id}/billing
            Method: POST
            RestApiId: !Ref Api
  SchoolsPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}
            Method: GET
            RestApiId: !Ref Api
  SchoolsIdMembershipsPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/memberships/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/memberships
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdMembershipsGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/memberships/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/memberships
            Method: GET
            RestApiId: !Ref Api
  SchoolsIdClassesPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/classes/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/classes
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdClassesGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/classes/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/classes
            Method: GET
            RestApiId: !Ref Api
  SchoolsIdInvitesPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/invites/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/invites
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdInvitesGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/invites/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/invites
            Method: GET
            RestApiId: !Ref Api
  SchoolsIdInvitesDELETE:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/invites/DELETE/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/invites
            Method: DELETE
            RestApiId: !Ref Api
  SchoolsIdJoinPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/join/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/join
            Method: POST
            RestApiId: !Ref Api
  SchoolsIdStudentsGET:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/students/GET/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/students
            Method: GET
            RestApiId: !Ref Api
  SchoolsIdStudentsPatch:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/students/{studentId}/PATCH/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/students/{studentId}
            Method: PATCH
            RestApiId: !Ref Api
  SchoolsIdKioskPOST:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/schools/{id}/kiosk/POST/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schools/{id}/kiosk
            Method: POST
            RestApiId: !Ref Api
  WebhookStripe:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/webhooks/stripe/index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /stripe
            Method: POST
            RestApiId: !Ref Webhooks
  ApiLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - nodejs14.x
      Description: API Layer
      LayerName: api